-- -- Works
-- SELECT
--     CategoryName,
--     Ammount,
--     SumOfAmmount,
--     Ammount - SumOfAmmount 
-- FROM (
--     SELECT
--         Categories.CategoryName,
--         Categories.Ammount, 
--         IFNULL(Sum(SpendingTransactions.Ammount), 0) AS SumOfAmmount
--     FROM
--         Categories 
--     LEFT JOIN SpendingTransactions ON Categories.CategoryName = SpendingTransactions.Category
--     GROUP BY
--     Categories.CategoryName,
--     Categories.Ammount
-- ) AS budget;

-- -- Works with totals
-- SELECT
--     CategoryName,
--     Ammount,
--     SumOfAmmount,
--     Ammount - SumOfAmmount AS Leftover
-- FROM (
--     SELECT
--         Categories.CategoryName,
--         Categories.Ammount, 
--         IFNULL(Sum(SpendingTransactions.Ammount), 0) AS SumOfAmmount
--     FROM
--         Categories 
--     LEFT JOIN SpendingTransactions ON Categories.CategoryName = SpendingTransactions.Category
--     GROUP BY
--     Categories.CategoryName,
--     Categories.Ammount
-- ) AS budget
-- UNION SELECT
--     "Total" AS CategoryName,
--     Sum(Ammount) AS Ammount,
--     Sum(SumOfAmmount) AS SumOfAmmount,
--     Sum(Ammount - SumOfAmmount) AS Leftover
-- FROM (
--     SELECT
--         Categories.CategoryName,
--         Categories.Ammount, 
--         IFNULL(Sum(SpendingTransactions.Ammount), 0) AS SumOfAmmount
--     FROM
--         Categories 
--     LEFT JOIN SpendingTransactions ON Categories.CategoryName = SpendingTransactions.Category
--     GROUP BY
--     Categories.CategoryName,
--     Categories.Ammount
-- ) AS budget